---
# file: roles/macbook_pro/tasks/main.yml

- name: Install standard brew Packages
  homebrew:
    name: [
      'zsh', 
      'htop'
    ]
    state: present

- name: Install standard brew cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
  - iterm2
  - rectangle

- name: Ammend zsh specific settings
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/zsh
    state: present
    regexp: '^/usr/local/bin/zsh'

- name: Change the default shell to zsh
  shell: chsh -s /usr/local/bin/zsh
  when: ansible_user_shell != "/usr/local/bin/zsh"

- name: Install Oh My zsh
  shell: 
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: "{{ lookup('env','HOME') }}/.oh-my-zsh"

- name: Install zsh plugins
  homebrew:
    name: [
      'romkatv/powerlevel10k/powerlevel10k',
      'zsh-syntax-highlighting',
      'zsh-autosuggestions',
      'zsh-history-substring-search'
    ]
    state: present

- name: Install zsh powerlevel10k theme into .zshrc
  lineinfile:
    path: "{{ lookup('env','HOME') }}//.zshrc"
    line: "source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme"
    state: present

- name: Install zsh plugins into .zshrc
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    line: "source /usr/local/share/{{ item }}/{{ item }}.zsh"
    state: present
  with_items:
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh-history-substring-search

- name: Ammend zsh plugins settings
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    line: plugins=(alias-finder brew common-aliases copydir copyfile docker docker-compose dotenv encode64 extract git jira jsontools node npm npx osx urltools vi-mode vscode web-search z)
    state: present
    regexp: '^plugins='

# plugins=(alias-finder brew common-aliases copydir copyfile docker docker-compose dotenv encode64 extract git jira jsontools node npm npx osx urltools vi-mode vscode web-search z)